### ISSUE TITLE
Add issue tracker notifications

### ISSUE THREAD

**Issue by edlefebvre** [hubot-scripts/hubot-bitbucket-pr#9]
Hi there!
Is it possible to notify issues as you do for pull requests?

Thank you for your help (and for this great script :-) )

**Comment by tshedor** [comment]
@edlefebvre I'm unfamiliar with Bitbucket Issues, although the Webhook documentation looks very similar to the PR and seems to be an easy feature addition. Since I've never used Issues, could you call out the relevant pieces of information that would come with a new/updated issue? Based on the documentation, I see these fields available:

* `component`
* `priority`
* `state`
* `type`
* `milestone`
* `version`

Preferably, I'd like to aim for, at max, 4 fields (excluding link, author, title, and repository name).

**Comment by edlefebvre** [comment]
@tshedor thank you for your answer!

Here are the fields I find important for the new/updated issue:

- type
- priority
- state

**Comment by tshedor** [comment]
Resolved in #10
